var searchData=
[
  ['capable_20queue_0',['2. Creating a Vulkan Device with a Graphics Capable Queue',['../md_docs_2hello-triangle.html#autotoc_md12',1,'']]],
  ['chainload_20toolchain_1',['4.1.2. Set the Proper Triplet and Chainload Toolchain',['../md_docs_2using-vku.html#autotoc_md43',1,'']]],
  ['check_20your_20first_20triangle_20with_20debuggers_2',['5.1. Check Your First Triangle with Debuggers',['../md_docs_2hello-triangle.html#autotoc_md24',1,'']]],
  ['clang_3',['Clang',['../md_docs_2using-vku.html#autotoc_md37',1,'3.3. Linux + Clang'],['../md_docs_2using-vku.html#autotoc_md36',1,'&lt;a name=&quot;macos-clang&quot;&gt;&lt;/a&gt;3.2. macOS + Clang']]],
  ['clang_20a_203_202_20macos_20clang_4',['&lt;a name=&quot;macos-clang&quot;&gt;&lt;/a&gt;3.2. macOS + Clang',['../md_docs_2using-vku.html#autotoc_md36',1,'']]],
  ['cmake_20project_5',['4. Directly use &lt;em&gt;vku&lt;/em&gt; in Your CMake Project',['../md_docs_2using-vku.html#autotoc_md40',1,'']]],
  ['cmake_20s_20tt_20fetchcontent_20tt_20or_20tt_20cpm_20cmake_20tt_6',['4.2. Using CMake&apos;s &lt;tt&gt;FetchContent&lt;/tt&gt; or &lt;tt&gt;CPM.cmake&lt;/tt&gt;',['../md_docs_2using-vku.html#autotoc_md44',1,'']]],
  ['cmake_20tt_7',['4.2. Using CMake&apos;s &lt;tt&gt;FetchContent&lt;/tt&gt; or &lt;tt&gt;CPM.cmake&lt;/tt&gt;',['../md_docs_2using-vku.html#autotoc_md44',1,'']]],
  ['code_8',['code',['../structvku_1_1Shader.html#ac28de1579bef1eb2c5442f7c8f6cfedd',1,'vku::Shader']]],
  ['colorattachmentinfo_9',['ColorAttachmentInfo',['../structvku_1_1AttachmentGroup_1_1ColorAttachmentInfo.html',1,'vku::AttachmentGroup::ColorAttachmentInfo'],['../structvku_1_1MsaaAttachmentGroup_1_1ColorAttachmentInfo.html',1,'vku::MsaaAttachmentGroup::ColorAttachmentInfo']]],
  ['command_20buffer_20and_20submitting_20the_20rendering_20commands_20into_20the_20queue_10',['5. Recording the Command Buffer and Submitting the Rendering Commands into the Queue',['../md_docs_2hello-triangle.html#autotoc_md22',1,'']]],
  ['commands_20into_20the_20queue_11',['5. Recording the Command Buffer and Submitting the Rendering Commands into the Queue',['../md_docs_2hello-triangle.html#autotoc_md22',1,'']]],
  ['commands_2ecppm_12',['commands.cppm',['../commands_8cppm.html',1,'']]],
  ['compilers_20and_20build_20tools_13',['2.2. Compilers and Build Tools',['../md_docs_2using-vku.html#autotoc_md33',1,'']]],
  ['config_14',['Config',['../structvku_1_1Gpu_1_1Config.html',1,'vku::Gpu']]],
  ['configuration_20options_15',['5. Configuration Options',['../md_docs_2using-vku.html#autotoc_md45',1,'']]],
  ['constants_2ecppm_16',['constants.cppm',['../constants_8cppm.html',1,'']]],
  ['cpm_20cmake_20tt_17',['4.2. Using CMake&apos;s &lt;tt&gt;FetchContent&lt;/tt&gt; or &lt;tt&gt;CPM.cmake&lt;/tt&gt;',['../md_docs_2using-vku.html#autotoc_md44',1,'']]],
  ['createstagingdstbuffer_18',['createStagingDstBuffer',['../classvku_1_1MappedBuffer.html#a3454cd9635014866ba6ce001baece527',1,'vku::MappedBuffer']]],
  ['creating_20a_20vulkan_20device_20with_20a_20graphics_20capable_20queue_19',['2. Creating a Vulkan Device with a Graphics Capable Queue',['../md_docs_2hello-triangle.html#autotoc_md12',1,'']]],
  ['creating_20buffer_20for_20de_20staging_20',['6.1. Creating Buffer for De-staging',['../md_docs_2hello-triangle.html#autotoc_md26',1,'']]],
  ['creating_20the_20graphics_20pipeline_21',['Creating the Graphics Pipeline',['../md_docs_2hello-triangle.html#autotoc_md17',1,'4. Creating the Graphics Pipeline'],['../md_docs_2hello-triangle.html#autotoc_md19',1,'4.2. Creating the Graphics Pipeline']]],
  ['creating_20the_20image_20to_20be_20rendered_22',['3. Creating the Image to Be Rendered',['../md_docs_2hello-triangle.html#autotoc_md14',1,'']]],
  ['creating_20the_20image_20view_23',['3.1. Creating the Image View',['../md_docs_2hello-triangle.html#autotoc_md16',1,'']]],
  ['creating_20vulkan_20instance_24',['1. Creating Vulkan Instance',['../md_docs_2hello-triangle.html#autotoc_md9',1,'']]],
  ['creation_25',['4.1. Shader module creation',['../md_docs_2hello-triangle.html#autotoc_md18',1,'']]]
];
