var searchData=
[
  ['mappedbuffer_0',['MappedBuffer',['../classvku_1_1MappedBuffer.html#affdf77019949f23ebcbe6ec7fafbafde',1,'vku::MappedBuffer::MappedBuffer(vma::Allocator allocator, std::from_range_t, R &amp;&amp;r, vk::BufferUsageFlags usage, vk::ArrayProxy&lt; const std::uint32_t &gt; queueFamilyIndices, const vma::AllocationCreateInfo &amp;allocationCreateInfo={ vma::AllocationCreateFlagBits::eHostAccessSequentialWrite|vma::AllocationCreateFlagBits::eMapped, vma::MemoryUsage::eAuto, })'],['../classvku_1_1MappedBuffer.html#a977bd4acc69ffbb13ed55671e4e34e71',1,'vku::MappedBuffer::MappedBuffer(vma::Allocator allocator, std::from_range_t, R &amp;&amp;r, vk::BufferUsageFlags usage, const vma::AllocationCreateInfo &amp;allocationCreateInfo={ vma::AllocationCreateFlagBits::eHostAccessSequentialWrite|vma::AllocationCreateFlagBits::eMapped, vma::MemoryUsage::eAuto, })'],['../classvku_1_1MappedBuffer.html#ad0bf93cf7b3aeeddad83ea6511655200',1,'vku::MappedBuffer::MappedBuffer(vma::Allocator allocator, const T &amp;value, vk::BufferUsageFlags usage, vk::ArrayProxy&lt; const std::uint32_t &gt; queueFamilyIndices, const vma::AllocationCreateInfo &amp;allocationCreateInfo={ vma::AllocationCreateFlagBits::eHostAccessSequentialWrite|vma::AllocationCreateFlagBits::eMapped, vma::MemoryUsage::eAuto, })'],['../classvku_1_1MappedBuffer.html#aa8518cf18faffc792ec9fbd3ddc023bd',1,'vku::MappedBuffer::MappedBuffer(vma::Allocator allocator, const vk::BufferCreateInfo &amp;createInfo, const vma::AllocationCreateInfo &amp;allocationCreateInfo={ vma::AllocationCreateFlagBits::eHostAccessSequentialWrite|vma::AllocationCreateFlagBits::eMapped, vma::MemoryUsage::eAuto, })'],['../classvku_1_1MappedBuffer.html#ad341b2e0f42f359abf20b99ada5e2e8a',1,'vku::MappedBuffer::MappedBuffer(vma::Allocator allocator, const T &amp;value, vk::BufferUsageFlags usage, const vma::AllocationCreateInfo &amp;allocationCreateInfo={ vma::AllocationCreateFlagBits::eHostAccessSequentialWrite|vma::AllocationCreateFlagBits::eMapped, vma::MemoryUsage::eAuto, })'],['../classvku_1_1MappedBuffer.html',1,'vku::MappedBuffer']]],
  ['mappedbuffer_2ecppm_1',['MappedBuffer.cppm',['../MappedBuffer_8cppm.html',1,'']]],
  ['maxmiplevels_2',['maxMipLevels',['../structvku_1_1Image.html#a5837faef891cbe9979cb8cc90452f1f3',1,'vku::Image::maxMipLevels(const vk::Extent3D &amp;extent) noexcept'],['../structvku_1_1Image.html#a5d4d236b29ba358b134e0771507b3f32',1,'vku::Image::maxMipLevels(const vk::Extent2D &amp;extent) noexcept'],['../structvku_1_1Image.html#ab11917aec069f52b661c82db4603374f',1,'vku::Image::maxMipLevels(std::uint32_t size) noexcept']]],
  ['mipextent_3',['mipExtent',['../structvku_1_1Image.html#a1b39478636039d8e149495fb229bd854',1,'vku::Image::mipExtent(const vk::Extent3D &amp;extent, std::uint32_t mipLevel) noexcept'],['../structvku_1_1Image.html#a574f8b9d84844f194559d8092b84cfab',1,'vku::Image::mipExtent(const vk::Extent2D &amp;extent, std::uint32_t mipLevel) noexcept'],['../structvku_1_1Image.html#a468b935ab9f22267a5addbcfbe6dd1af',1,'vku::Image::mipExtent(std::uint32_t mipLevel) const noexcept']]],
  ['mipextent2d_4',['mipExtent2D',['../structvku_1_1Image.html#a9f8b319c4b752b9bcc823a53f25c666f',1,'vku::Image']]],
  ['miplevels_5',['mipLevels',['../structvku_1_1Image.html#a905018936a2d315777361cf1206c7e2b',1,'vku::Image']]],
  ['mod_2ecppm_6',['mod.cppm',['../utils_2mod_8cppm.html',1,'(Global Namespace)'],['../rendering_2mod_8cppm.html',1,'(Global Namespace)'],['../pipelines_2mod_8cppm.html',1,'(Global Namespace)'],['../mod_8cppm.html',1,'(Global Namespace)'],['../images_2mod_8cppm.html',1,'(Global Namespace)'],['../descriptors_2mod_8cppm.html',1,'(Global Namespace)'],['../buffers_2mod_8cppm.html',1,'(Global Namespace)']]],
  ['msaaattachment_7',['MsaaAttachment',['../structvku_1_1MsaaAttachment.html',1,'vku']]],
  ['msaaattachment_2ecppm_8',['MsaaAttachment.cppm',['../MsaaAttachment_8cppm.html',1,'']]],
  ['msaaattachmentgroup_9',['MsaaAttachmentGroup',['../structvku_1_1MsaaAttachmentGroup.html',1,'vku']]],
  ['msaaattachmentgroup_2ecppm_10',['MsaaAttachmentGroup.cppm',['../MsaaAttachmentGroup_8cppm.html',1,'']]]
];
