name: Linux

on:
  push:
    paths:
      - '**'
      - '!.github/workflows/**'
      - '.github/workflows/linux.yml'

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - c_compiler: gcc-14
            cxx_compiler: g++-14
          - c_compiler: clang-18
            cxx_compiler: clang++-18

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1

      - name: Configure
        run: |
          mkdir build
          CC=${{ matrix.compiler.c_compiler }}                                               \
          CXX=${{ matrix.compiler.cxx_compiler }}                                            \
          cmake -S . -B build                                                                \
            -DCMAKE_BUILD_TYPE=Release                                                       \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVKU_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build build --config Release