name: Linux

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

on:
  push:
    paths:
      - '**'
      - '!README.md'
      - '!LICENSE.txt'
      - '!docs/**'
      - '!.github/workflows/*.yml'
      - '.github/workflows/linux.yml'

jobs:
  build:
    strategy:
      matrix:
        build: [Debug, Release]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get install libxrandr-dev ninja-build libc++-dev libc++abi-dev

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg && ./bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $GITHUB_ENV

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Apply patch for vcpkg-based dependency management
        run: git apply vcpkg-deps.patch

      - name: Configure
        run: |
          mv .github/workflows/CMakeUserPresets.json .
          cmake --preset=clang -DCMAKE_BUILD_TYPE=${{ matrix.build }}

      - name: Install
        run: cmake --build build --target install