name: Windows

on:
  push:
    paths:
      - '**'
      - '!.github/workflows/**'
      - '.github/workflows/windows.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build -G "Visual Studio 17 2022" -T v143                                   `
            -DCMAKE_BUILD_TYPE=Release                                                             `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVKU_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build build --config Release